### ISSUE TITLE
Every country is Wales?

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/political_tweets#29]
![screen shot 2015-08-27 at 13 24 42](https://cloud.githubusercontent.com/assets/57483/9520426/0f4db8d4-4cbf-11e5-8117-3f9d005b8d29.png)

**Comment by zarino** [comment]
That's because Wales is awesome!

**Comment by zarino** [comment]
If @chrismytton can make `app/jobs/jekyll_site_generator_job.rb` add the country name to the `_config.yml` it generates, then I can access it in the template using `{{ site.country }}` or similar.

**Comment by chrismytton** [comment]
This is kinda tricky because we actually want it to display the full legislature name, something like "Welsh Assembly". However we only have "Wales" as the country name and "Assembly" as the legislature name, so creating Welsh assembly is not currently possible. There was some previous discussion about this but I can't find a ticket to reference.

**Comment by zarino** [comment]
I remember that discussion too, but can't find the ticket in any of the everypolitician repos. It might have been in Slack instead?

Anyway, in the meantime, can't we just use the country name?

**Comment by tmtmtmtm** [comment]
What about just using the country name if there's only legislature for the country, and using "country name (legislature)" where there's more than one?

**Comment by chrismytton** [comment]
I've gone with @tmtmtmtm's suggestion and displayed the name of the legislature in brackets _only_ if there's more than one legislature for the given countries. Pull Request here - https://github.com/mysociety/SeePoliticiansTweet/pull/55
